In [ ]:
avg

In [ ]:

number1 = float(input("Enter the first number: "))
number2 = float(input("Enter the second number: "))

average = (number1 + number2) / 2

print("The average of", number1, "and", number2, "is", average)


Enter the first number: 6
Enter the second number: 6
The average of 6.0 and 6.0 is 6.0


In [ ]:
def mul (num):
  for i in range (1,11):
    mul=num*i;
    if (i==6):
      continue;
    print (num, "x" , i, "=", mul);
    if (i==8):
      break;

num = int(input("Enter the first number: "))
print ("Multiplication")
mul(num)



Enter the first number: 5
Multiplication
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 7 = 35
5 x 8 = 40


In [ ]:
def mul(num):
  for i in range(1,11):
    num=6;
    c=6*i;

    if i==6:
      continue;
    if i==9:
      break;
    print (num, "x" , i, "=", mul);
    mul(num);

In [ ]:
list1 = [1,2,3,4,5]
sum=0
for i in list1:
  if i%2==0:
    sum = sum+i
print (f"sum of even = {sum}")

sum of even = 6


In [ ]:
list1 = [1,2,3,4,5]
even= 0
odd= 0

for i in list1:
  if i % 2 == 0:
    sum=sum+i
    even+= 1
  else:
    odd+= 1



print(f"Even numbers: {even}")
print(f"Odd numbers: {odd}")


Even numbers: 2
Odd numbers: 3


In [ ]:
a = [1, 3, 5, 7, 4]


length_of_list = len(a)
print("Length:", length_of_list)


type_of_list = type(a)
print("Type:", type_of_list)


element_in_neg2 = a[-2]
print("index -2:", element_in_neg2)


element_in_2 = a[2]
print("index 2:", element_in_2)


Length: 5
Type: <class 'list'>
index -2: 7
index 2: 5


In [ ]:
a = [1, 3, 5, 7, 4]

a[-3] = 50
print("Updated list:", a)

slice_2_4 = a[2:4]
slice_to_neg3 = a[:-3]
slice_neg4_to_neg1 = a[-4:-1]

print("a[2:4]:", slice_2_4)
print("a[:-3]:", slice_to_neg3)
print("a[-4:-1]:", slice_neg4_to_neg1)


a.append(100)
a[2] = 200
print("Updated list:", a)

a.pop()
print ("After remove", a)
a.pop(1)
print ("After delete", a)




Updated list: [1, 3, 50, 7, 4]
a[2:4]: [50, 7]
a[:-3]: [1, 3]
a[-4:-1]: [3, 50, 7]
Updated list: [1, 3, 200, 7, 4, 100]
After remove [1, 3, 200, 7, 4]
After delete [1, 200, 7, 4]


set

In [ ]:
a = {1, 3, 5, 8, 3, 7}
b = {0, False, 1, 5}


print("Length'a':", len(a))
print("Length'b':", len(b))
print("Type'a':", type(a))
print("Type'b':", type(b))

a.add(10)
print("Updated Set:",a)

a.remove(8)
print ("After Removed Set:",a)

union_ab = a | b
intersection_ab = a & b
difference_ab = a - b

print("Union a and b:", union_ab)
print("Intersection a and b:", intersection_ab)
print("Difference (a - b):", difference_ab)

for element in a:
    print(element)

    if element == 5:

       break




list = [2,3,4]

new_set = set(list)
result = a.union(new_set)
print(result)



Length'a': 5
Length'b': 3
Type'a': <class 'set'>
Type'b': <class 'set'>
Updated Set: {1, 3, 5, 7, 8, 10}
After Removed Set: {1, 3, 5, 7, 10}
Union a and b: {0, 1, 3, 5, 7, 10}
Intersection a and b: {1, 5}
Difference (a - b): {10, 3, 7}
1
3
5
{1, 2, 3, 4, 5, 7, 10}


In [ ]:
from collections.abc import MutableMapping
Employee = {
    "name": "A",
    "age": 40,
    "type": {
        "developer": ["ios", "android"]
    },
    "parmanent": True,
    "Salary": 3000,
    100: (1, 2, 3),
    4.5: {5, 6, True, 7, 1}
}


print("Length of Employee:", len(Employee))
print("Type of Employee :", type(Employee))


developer_types = Employee["type"]["developer"]
print("Developer types:", developer_types)

Employee["parmanent"] = False

print("After update:", Employee)





Length of Employee: 7
Type of Employee : <class 'dict'>
Developer types: ['ios', 'android']
After update: {'name': 'A', 'age': 40, 'type': {'developer': ['ios', 'android']}, 'parmanent': False, 'Salary': 3000, 100: (1, 2, 3), 4.5: {True, 5, 6, 7}}


In [ ]:
class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * (self.length + self.width)


rect = Rectangle(5, 3)
print("Area:", rect.area())
print("Perimeter:", rect.perimeter())


Area: 15
Perimeter: 16


In [ ]:
class Shape:
    def __init__(self, name):
        self.name = name
    def get_name(self):
        return self.name

class Rectangle(Shape):
    def __init__(self, length, width):
        super().__init__("Rectangle")
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * (self.length + self.width)

r1 = Rectangle(6, 5)
print("Shape:", r1.get_name())
print("Area:", r1.area())
print("Perimeter:", r1.perimeter())
r2 = Rectangle(3, 4)
print("Shape:", r2.get_name())
print("Area:", r2.area())
print("Perimeter:", r2.perimeter())


Shape: Rectangle
Area: 30
Perimeter: 22
Shape: Rectangle
Area: 12
Perimeter: 14


In [ ]:
class Shape:
    def __init__(self, name):
        self._name = name

    def __display_shape_type(self):
        print(f"Shape of type: {self._name}")
    def display(self):
        self.__display_shape_type()


class Rectangle(Shape):
    def __init__(self, length, width):
        super().__init__("Rectangle")
        self.__length = length
        self.__width = width

    def get_length(self):
        return self.__length

    def get_width(self):
        return self.__width




r1= Rectangle(5, 3)
r1.display()
print("length:",r1.get_length())
print("width:",r1.get_width())

Shape of type: Rectangle
length: 5
width: 3


In [ ]:
import numpy as np
num= np.array ([2,3,4,5])
print (num)
type(num)

[2 3 4 5]


numpy.ndarray

In [ ]:
array_1D= np.array([2,4,5,6])
array_1D

array([2, 4, 5, 6])

In [ ]:
array_2D= np.array([[2,4,5,6],[2,4,5,6],[2,4,5,6]])
array_2D

array([[2, 4, 5, 6],
       [2, 4, 5, 6],
       [2, 4, 5, 6]])

In [ ]:
array_3D= np.array([[[2,4,5,6],[2,4,5,6],[2,4,5,6]]])
array_3D

array([[[2, 4, 5, 6],
        [2, 4, 5, 6],
        [2, 4, 5, 6]]])

In [ ]:
import numpy as np
output = np.array([[x for x in range(2,21,2)],[x for x in range(1,21,2)]])
output

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [ ]:
ary=np.array([[1,2,3],[4,5,6]])
print(ary)
print(ary.dtype)
print(ary.ndim)
print(ary.shape)
print(ary.size)
print(ary.itemsize)

[[1 2 3]
 [4 5 6]]
int64
2
(2, 3)
6
8


In [ ]:
ary= np.array([[1,2,3],[4,5,6]])
print(ary)
print(ary>5)
print(ary<=5)
print(ary==5)
print(ary.max())
print(ary.min())
print(ary.sum())
print(ary.std())
print(ary.mean())
print(ary.var())
print(ary.mean(axis=0))
print(ary.mean(axis=1))



[[1 2 3]
 [4 5 6]]
[[False False False]
 [False False  True]]
[[ True  True  True]
 [ True  True False]]
[[False False False]
 [False  True False]]
6
1
21
1.707825127659933
3.5
2.9166666666666665
[2.5 3.5 4.5]
[2. 5.]


In [ ]:
num1=np.arange(1,6)
print(num1)
num2=num1.view()
print(num2)

print(id(num1))
print(id(num2))

num2[1]*=5
print(num1)
print(num2)

[1 2 3 4 5]
[1 2 3 4 5]
134842304069328
134842304064624
[ 1 10  3  4  5]
[ 1 10  3  4  5]


In [ ]:
num1=np.arange(1,6)
print(num1)
num2=num1.copy()
num2

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [ ]:

import numpy as np

scr = np.array([85,90,78,92,88])

scr = scr.astype('f')

print(scr)
print(scr.dtype)

ascr=scr.copy()
print(ascr)
print(ascr+5)

print(scr.dtype)
print(scr.ndim)
print(scr.shape)
print(scr.size)
print(scr.itemsize)
print(np.sort(scr))

x= np.where (scr > 85)
print (x)

print(scr.max())
print(scr.min())
print(scr.sum())
print(scr.std())
print(scr.mean())
print(scr.var())
print(scr.mean(axis=0))

print(scr[::2])
print(scr[-3:-1])
print(scr[1:4])
print(scr[::-1])








[85. 90. 78. 92. 88.]
float32
[85. 90. 78. 92. 88.]
[90. 95. 83. 97. 93.]
float32
1
(5,)
5
4
[78. 85. 88. 90. 92.]
(array([1, 3, 4]),)
92.0
78.0
433.0
4.8826222
86.6
23.84
86.6
[85. 78. 88.]
[78. 92.]
[90. 78. 92.]
[88. 92. 78. 90. 85.]


In [7]:
import random

class Character:
    def __init__(self, name, health, attack_damage):
        self.name = name
        self.health = health
        self.attack_damage = attack_damage

    def get_name(self):
        return self.name

    def get_health(self):
        return self.health

    def take_damage(self, damage):
        self.health -= damage

    def attack(self):
        return self.attack_damage

    def is_alive(self):
        return self.health > 0

class Player(Character):
    def __init__(self, name, health, attack_damage):
        super().__init__(name, health, attack_damage)

    def display_status(self):
        print(f"Player Status: {self.get_name()} | Health: {self.get_health()}")

class Monster(Character):
    def __init__(self, name, health, attack_damage):
        super().__init__(name, health, attack_damage)

class Dungeon:
    def __init__(self, player):
        self.player = player
        self.current_monster = self.generate_random_monster()

    def generate_random_monster(self):
        monster_names = ["Goblin", "Orc", "Troll", "Dragon"]
        random_monster_name = random.choice(monster_names)
        random_health = random.randint(50, 100)
        random_attack_damage = random.randint(10, 20)
        return Monster(random_monster_name, random_health, random_attack_damage)

    def start(self):
        print("Welcome to the Dungeon!")
        while self.player.is_alive():
            print("\n-----------------------------")
            self.player.display_status()
            print(f"A wild {self.current_monster.get_name()} appears!")

            # Player attacks the monster
            player_damage = self.player.attack()
            self.current_monster.take_damage(player_damage)
            print(f"You attack for {player_damage} damage.")

            # Check if the monster is defeated
            if not self.current_monster.is_alive():
                print(f"You defeated the {self.current_monster.get_name()}!")
                self.current_monster = self.generate_random_monster()
                continue

            # Monster attacks the player
            monster_damage = self.current_monster.attack()
            self.player.take_damage(monster_damage)
            print(f"{self.current_monster.get_name()} attacks for {monster_damage} damage.")

            # Check if the player is defeated
            if not self.player.is_alive():
                print(f"You were defeated by the {self.current_monster.get_name()}. Game over!")
                break

if __name__ == "__main__":
    player = Player("Adventurer", 100, 15)
    dungeon = Dungeon(player)
    print(dungeon)